<template>
    <div
        class="aspect-2 relative left-[10%] -mt-[10%] mb-[10%] flex w-full max-w-[90%] flex-1 overflow-hidden rounded-sm border border-gray-400/30 bg-white shadow-xl p-[3%]">
        <div class="grid h-full w-full grid-cols-7 grid-rows-5 gap-x-[2.5%] gap-y-[5%] font-mono text-[min(2vw,12px)]">
            <!-- Suggestions Section -->
            <div class="col-span-3 row-span-3 bg-gradient-to-br from-gray-50 to-white p-[8%]">
                <div
                    class="flex h-full w-full flex-col gap-[6.5%] [&_span]:h-full [&_span]:rounded-full [&_span]:bg-gray-300">
                    <div class="font-semibold uppercase tracking-wider">Suggestions</div>
                    <span class="w-full"></span>
                    <span class="w-full"></span>
                    <span class="w-full"></span>
                    <span class="w-full"></span>
                    <span class="w-full"></span>
                    <span class="w-full"></span>
                    <span class="w-[78%]"></span>
                </div>
            </div>

            <!-- Code Analysis Section -->
            <div class="col-span-4 row-span-4 bg-gradient-to-bl from-gray-50 to-white p-[5.5%]">
                <div class="flex h-full flex-col items-stretch justify-between">
                    <div class="font-semibold uppercase tracking-wider">Code Analysis</div>
                    <div class="my-[5%] flex items-center text-[min(2.5vw,20px)] lg:text-[min(1.2vw,20px)]">
                        <div class="flex items-center gap-[4%]">
                            <span class="font-bold text-yellow-500">4.5</span>
                            <!-- Placeholder for star rating -->
                            <div class="text-yellow-500">★★★★☆</div>
                        </div>
                    </div>

                    <!-- Metrics List -->
                    <dl class="flex flex-1 flex-col justify-between text-[min(2vw,11px)] lg:text-[min(0.8vw,11px)]">
                        <div v-for="metric in metrics" :key="metric.name" class="flex items-center gap-[5%]">
                            <span class="min-w-[30%]">{{ metric.name }}</span>
                            <div class="relative h-[35%] flex-1">
                                <div
                                    class="h-full w-full rounded-full border border-gray-200 dark:border-gray-800 bg-gray-100">
                                </div>
                                <div class="absolute inset-y-0 rounded-full border border-yellow-400 bg-yellow-400"
                                    :style="{ width: metric.value + '%' }"></div>
                            </div>
                            <span class="text-right tabular-nums text-gray-900">{{ metric.value }}%</span>
                        </div>
                    </dl>
                </div>
            </div>

            <!-- Summary Section -->
            <div class="col-span-3 row-span-2 bg-gradient-to-tr from-gray-50 to-white p-[8%]">
                <div
                    class="flex h-full w-full flex-col gap-[13%] [&_span]:h-full [&_span]:rounded-full [&_span]:bg-gray-300">
                    <div class="font-semibold uppercase tracking-wider">Summary</div>
                    <span class="w-full"></span>
                    <span class="w-full"></span>
                    <span class="w-[78%]"></span>
                </div>
            </div>

            <!-- AI Generated Footer -->
            <div
                class="col-span-4 row-span-1 flex items-center justify-center rounded bg-gradient-to-r from-gray-800 via-gray-700 to-gray-800 px-[1%] text-[min(1.5vw,12px)] text-white lg:text-[min(0.7vw,12px)]">
                Generated by codedamn AI in 10 mins
            </div>
        </div>
    </div>
</template>

<script setup>
import { ref } from 'vue';

const metrics = ref([
    { name: 'Performance', value: 87 },
    { name: 'Security', value: 78 },
    { name: 'Readability', value: 92 },
    { name: 'Accuracy', value: 89 }
]);
</script>